services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "andros-super-random-key-2025-x3"
      SECRET: “plazos-con-pasos-azar”
      ADMIN_EMAIL: "admin@androik.world"
      ADMIN_PASSWORD: “Androd1r3_25"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
